use crate::language::LangDef;
use crate::spec::{applies_to_lang, BasisSpec};

#[derive(Debug)]
pub struct GeneratedFile {
    pub relative_path: String,
    pub content: String,
}

fn resolve_preferred<'a>(lang: &'a LangDef, canonical: &'a str) -> &'a str {
    lang.preferred_type
        .iter()
        .find(|(k, _)| *k == canonical)
        .map(|(_, v)| *v)
        .unwrap_or(canonical)
}

pub fn generate(spec: &BasisSpec, lang: &LangDef) -> Result<Vec<GeneratedFile>, String> {
    let has_newtypes = spec.newtypes.as_ref().is_some_and(|n| {
        n.enabled && n.types.iter().any(|nt| applies_to_lang(&nt.languages, lang.name))
    });
    let has_unions = spec.exhaustive_matching.as_ref().is_some_and(|e| {
        e.enabled
            && e.unions
                .iter()
                .any(|u| applies_to_lang(&u.languages, lang.name))
    });

    if has_newtypes && lang.generate_newtype.is_none() {
        return Err(format!(
            "newtype generation not yet supported for {}",
            lang.name
        ));
    }
    if has_unions && (lang.generate_union.is_none() || lang.generate_match_scaffold.is_none()) {
        return Err(format!(
            "union generation not yet supported for {}",
            lang.name
        ));
    }

    let mut body = String::new();

    // Header comment
    body.push_str(&format!(
        "{} Generated by Basis — do not edit by hand.\n",
        lang.comment_prefix
    ));

    // Language-specific preamble
    if let Some(preamble) = lang.generate_preamble {
        let p = preamble(has_newtypes, has_unions);
        if !p.is_empty() {
            body.push_str(&p);
        }
    }
    body.push('\n');

    // Newtypes
    if let Some(newtypes) = &spec.newtypes {
        if newtypes.enabled && !newtypes.types.is_empty() {
            let gen = lang.generate_newtype.unwrap();
            body.push_str(&format!("{} ── Newtypes ──\n\n", lang.comment_prefix));
            for nt in &newtypes.types {
                if !applies_to_lang(&nt.languages, lang.name) {
                    continue;
                }
                let prim = resolve_preferred(lang, &nt.wraps);
                body.push_str(&gen(&nt.name, prim, nt.validation.as_deref()));
                body.push('\n');
            }
        }
    }

    // Unions + match scaffolds
    if let Some(exhaustive) = &spec.exhaustive_matching {
        if exhaustive.enabled && !exhaustive.unions.is_empty() {
            let gen_union = lang.generate_union.unwrap();
            let gen_match = lang.generate_match_scaffold.unwrap();
            body.push_str(&format!("{} ── Unions ──\n\n", lang.comment_prefix));
            for union_def in &exhaustive.unions {
                if !applies_to_lang(&union_def.languages, lang.name) {
                    continue;
                }
                body.push_str(&gen_union(&union_def.name, &union_def.variants));
                body.push('\n');
                body.push_str(&gen_match(&union_def.name, &union_def.variants));
                body.push('\n');
            }
        }
    }

    Ok(vec![GeneratedFile {
        relative_path: lang.type_file_name.to_string(),
        content: body,
    }])
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::language::LangRegistry;
    use crate::spec::{
        BasisSpec, ExhaustiveConfig, Governance, NewtypeConfig, NewtypeDef, UnionDef,
    };

    fn test_spec() -> BasisSpec {
        BasisSpec {
            governance: Governance::new("1.0"),
            extends: None,
            layers: Default::default(),
            newtypes: Some(NewtypeConfig {
                enabled: true,
                types: vec![
                    NewtypeDef {
                        name: "UserId".to_string(),
                        wraps: "string".to_string(),
                        validation: Some("uuid_v4".to_string()),
                        languages: None,
                    },
                    NewtypeDef {
                        name: "OrderId".to_string(),
                        wraps: "string".to_string(),
                        validation: Some("uuid_v4".to_string()),
                        languages: None,
                    },
                    NewtypeDef {
                        name: "Amount".to_string(),
                        wraps: "float".to_string(),
                        validation: None,
                        languages: None,
                    },
                ],
                exclude_params: vec![],
                exclude_functions: vec![],
            }),
            exhaustive_matching: Some(ExhaustiveConfig {
                enabled: true,
                unions: vec![UnionDef {
                    name: "OrderStatus".to_string(),
                    variants: vec![
                        "Pending".to_string(),
                        "Confirmed".to_string(),
                        "Shipped".to_string(),
                        "Delivered".to_string(),
                        "Cancelled".to_string(),
                    ],
                    languages: None,
                }],
            }),
            purity: None,
            boundaries: None,
        }
    }

    #[test]
    fn generate_skips_language_scoped_newtype() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("python").unwrap();
        let mut spec = test_spec();
        // Add a JS-only newtype
        if let Some(newtypes) = &mut spec.newtypes {
            newtypes.types.push(NewtypeDef {
                name: "WindowId".to_string(),
                wraps: "int".to_string(),
                validation: None,
                languages: Some(vec!["js".to_string()]),
            });
        }
        let files = generate(&spec, lang).unwrap();
        let c = &files[0].content;
        assert!(c.contains("UserId"), "unscoped type should be present");
        assert!(!c.contains("WindowId"), "JS-only type should be skipped for Python");
    }

    #[test]
    fn generate_skips_language_scoped_union() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("python").unwrap();
        let mut spec = test_spec();
        // Add a JS-only union
        if let Some(exhaustive) = &mut spec.exhaustive_matching {
            exhaustive.unions.push(UnionDef {
                name: "IpcMessage".to_string(),
                variants: vec!["Open".to_string(), "Close".to_string()],
                languages: Some(vec!["js".to_string()]),
            });
        }
        let files = generate(&spec, lang).unwrap();
        let c = &files[0].content;
        assert!(c.contains("OrderStatus"), "unscoped union should be present");
        assert!(!c.contains("IpcMessage"), "JS-only union should be skipped for Python");
    }

    #[test]
    fn generate_python() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("python").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].relative_path, "types.py");
        let c = &files[0].content;
        assert!(c.contains("UserId = NewType(\"UserId\", str)"));
        assert!(c.contains("def validate_user_id(value: str) -> UserId:"));
        assert!(c.contains("Amount = NewType(\"Amount\", float)"));
        assert!(!c.contains("validate_amount")); // no validation for Amount
        assert!(c.contains("case \"Pending\":"));
        assert!(c.contains("case \"Cancelled\":"));
    }

    #[test]
    fn generate_rust() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("rust").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files[0].relative_path, "types.rs");
        let c = &files[0].content;
        assert!(c.contains("pub struct UserId(pub String)"));
        assert!(c.contains("pub fn new(value: String) -> Result<Self, String>"));
        assert!(c.contains("pub struct Amount(pub f64)"));
        assert!(c.contains("impl From<f64> for Amount")); // no validation
        assert!(c.contains("OrderStatus::Pending => todo!()"));
        assert!(c.contains("OrderStatus::Cancelled => todo!()"));
    }

    #[test]
    fn generate_go() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("go").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files[0].relative_path, "types.go");
        let c = &files[0].content;
        assert!(c.contains("package types"));
        assert!(c.contains("type UserId string"));
        assert!(c.contains("func NewUserId(value string) (UserId, error)"));
        assert!(c.contains("type Amount float64"));
        assert!(!c.contains("NewAmount")); // no validation
        assert!(c.contains("case Pending:"));
        assert!(c.contains("case Cancelled:"));
    }

    #[test]
    fn generate_typescript() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("js").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files[0].relative_path, "types.ts");
        let c = &files[0].content;
        assert!(c.contains("export type UserId = string & { readonly __brand: \"UserId\" }"));
        assert!(c.contains("throw new Error(\"not implemented\")"));
        assert!(c.contains("export type Amount = number & { readonly __brand: \"Amount\" }"));
        assert!(c.contains("return value as Amount")); // no validation = simple cast
        assert!(c.contains("case \"Pending\":"));
        assert!(c.contains("case \"Cancelled\":"));
    }

    #[test]
    fn generate_java() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("java").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files[0].relative_path, "Types.java");
        let c = &files[0].content;
        assert!(c.contains("public record UserId(String value)"));
        assert!(c.contains("public enum OrderStatus"));
        assert!(c.contains("case \"Pending\":"));
        assert!(c.contains("case \"Cancelled\":"));
    }

    #[test]
    fn generate_kotlin() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("kotlin").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files[0].relative_path, "Types.kt");
        let c = &files[0].content;
        assert!(c.contains("value class UserId(val value: String)"));
        assert!(c.contains("sealed class OrderStatus"));
        assert!(c.contains("\"Pending\" -> TODO()"));
        assert!(c.contains("\"Cancelled\" -> TODO()"));
    }

    #[test]
    fn generate_swift() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("swift").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files[0].relative_path, "Types.swift");
        let c = &files[0].content;
        assert!(c.contains("struct UserId"));
        assert!(c.contains("let rawValue: String"));
        assert!(c.contains("enum OrderStatus"));
        assert!(c.contains("case .Pending:"));
        assert!(c.contains("case .Cancelled:"));
    }

    #[test]
    fn generate_csharp() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("csharp").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files[0].relative_path, "Types.cs");
        let c = &files[0].content;
        assert!(c.contains("public readonly record struct UserId(string Value)"));
        assert!(c.contains("public enum OrderStatus"));
        assert!(c.contains("case \"Pending\":"));
        assert!(c.contains("case \"Cancelled\":"));
    }

    #[test]
    fn generate_ruby() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("ruby").unwrap();
        let files = generate(&test_spec(), lang).unwrap();
        assert_eq!(files[0].relative_path, "types.rb");
        let c = &files[0].content;
        assert!(c.contains("UserId = Data.define(:value)"));
        assert!(c.contains("def validate_user_id(value)"));
        assert!(c.contains("module OrderStatus"));
        assert!(c.contains("when \"Pending\""));
        assert!(c.contains("when \"Cancelled\""));
    }

    #[test]
    fn all_nine_languages_generate() {
        let registry = LangRegistry::new();
        let spec = test_spec();
        for name in &[
            "python", "rust", "js", "go", "java", "kotlin", "swift", "csharp", "ruby",
        ] {
            let lang = registry.for_name(name).unwrap();
            let result = generate(&spec, lang);
            assert!(
                result.is_ok(),
                "generation failed for {name}: {:?}",
                result.err()
            );
            assert!(
                !result.unwrap()[0].content.is_empty(),
                "empty output for {name}"
            );
        }
    }

    #[test]
    fn resolve_preferred_known() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("python").unwrap();
        assert_eq!(resolve_preferred(lang, "string"), "str");
        assert_eq!(resolve_preferred(lang, "int"), "int");
        assert_eq!(resolve_preferred(lang, "float"), "float");
    }

    #[test]
    fn resolve_preferred_unknown_passes_through() {
        let registry = LangRegistry::new();
        let lang = registry.for_name("python").unwrap();
        assert_eq!(resolve_preferred(lang, "custom_type"), "custom_type");
    }

    // ── Self-verification: dual-assertion tests ──
    // For each language: generated match scaffold with ALL variants → scan_matches → 0 hits
    // AND with ONE variant removed → scan_matches → 1 hit naming the missing variant

    use crate::language::MatchHit;
    use std::collections::HashSet;

    fn variants() -> Vec<String> {
        vec![
            "Pending".to_string(),
            "Confirmed".to_string(),
            "Shipped".to_string(),
            "Delivered".to_string(),
            "Cancelled".to_string(),
        ]
    }

    fn build_indices(
        union_name: &str,
        variants: &[String],
    ) -> (
        std::collections::HashMap<String, (String, HashSet<String>)>,
        std::collections::HashMap<String, HashSet<String>>,
    ) {
        let variant_set: HashSet<String> = variants.iter().cloned().collect();
        let mut vi = std::collections::HashMap::new();
        for v in variants {
            vi.insert(v.clone(), (union_name.to_string(), variant_set.clone()));
        }
        let mut um = std::collections::HashMap::new();
        um.insert(union_name.to_string(), variant_set);
        (vi, um)
    }

    fn self_verify(lang_name: &str) {
        let registry = LangRegistry::new();
        let lang = registry.for_name(lang_name).unwrap();
        let all_variants = variants();
        let gen_match = lang.generate_match_scaffold.unwrap();
        let (vi, um) = build_indices("OrderStatus", &all_variants);

        // Assertion 1: all variants → 0 hits
        let full_scaffold = gen_match("OrderStatus", &all_variants);
        let mut hits: Vec<MatchHit> = Vec::new();
        (lang.scan_matches)(&full_scaffold, "test", &vi, &um, &mut hits);
        assert!(
            hits.is_empty(),
            "[{lang_name}] full scaffold should produce 0 hits, got {}: {:?}",
            hits.len(),
            hits.iter().map(|h| &h.missing_variants).collect::<Vec<_>>()
        );

        // Assertion 2: remove last variant → 1 hit naming "Cancelled"
        let partial: Vec<String> = all_variants[..4].to_vec();
        let partial_scaffold = gen_match("OrderStatus", &partial);
        let mut hits2: Vec<MatchHit> = Vec::new();
        (lang.scan_matches)(&partial_scaffold, "test", &vi, &um, &mut hits2);
        assert_eq!(
            hits2.len(),
            1,
            "[{lang_name}] partial scaffold should produce 1 hit, got {}",
            hits2.len()
        );
        assert!(
            hits2[0].missing_variants.contains(&"Cancelled".to_string()),
            "[{lang_name}] missing variants should include 'Cancelled', got {:?}",
            hits2[0].missing_variants
        );
    }

    #[test]
    fn self_verify_python() {
        self_verify("python");
    }
    #[test]
    fn self_verify_rust() {
        self_verify("rust");
    }
    #[test]
    fn self_verify_go() {
        self_verify("go");
    }
    #[test]
    fn self_verify_typescript() {
        self_verify("js");
    }
    #[test]
    fn self_verify_java() {
        self_verify("java");
    }
    #[test]
    fn self_verify_kotlin() {
        self_verify("kotlin");
    }
    #[test]
    fn self_verify_swift() {
        self_verify("swift");
    }
    #[test]
    fn self_verify_csharp() {
        self_verify("csharp");
    }
    #[test]
    fn self_verify_ruby() {
        self_verify("ruby");
    }
}
